import { FormControl } from "@angular/forms";
import { Ecbm } from "../ecbm/ecbm";
import { MachineClass } from "./machine-classes";



interface Machine  {
    id: string;
    serialNo: string;
    orderNo: string;
    customer: string;
    machineClass: MachineClass;

    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    
    ecbms: Ecbm[];
}

// Machine Create form type
interface MachineCreateForm {
    serialNo: FormControl<string>;
    orderNo: FormControl<string>;
    customer: FormControl<string>;
    machineClassId: FormControl<string>;
}


// Omit properties to be generated by database and replace machineClass with machineClassId as we are not sending the full MachineClass object when creating a machine
type MachineCreate = Omit<Machine, 'id' | 'createdBy' | 'updatedBy' | 'createdAt' | 'updatedAt' | 'ecbms' | 'machineClass'> & { 
    machineClassId: string 
};

export type { Machine, MachineCreateForm, MachineCreate };